f=imread('cameraman.tif');
f=tofloat(f);
F=fft2(f);
S=fftshift(log(1+abs(F)));
figure (1);
imshow(S,[]);
h=fspecial('laplacian');
PQ=paddedsize(size(f));
H=freqz2(h,PQ(1),PQ(2));
H1=ifftshift(H);
figure (2);
imshow(abs(H),[]);
figure (3);
imshow(abs(H1),[]);
gs=imfilter(f,h,'conv');
gf=dftfilt(f,H1);
figure(4);
imshow(gs,[]);
figure (5);
imshow(gf,[]);
figure (6);
imshow(abs(gs),[]);
figure (7);
imshow(abs(gf),[]);
